<h2 class="ml-lg-5 py-lg-2 mx-1 display-3 font-weight-bold">Ups! Stránka nenájdená ...</h2>
<div class="row mx-lg-5 py-5 mx-2">
    <h4 class="offset-lg-1 col-lg-7">
        Táto stránka sa vám zobrazila, pretože adresa, ktorú ste zadali alebo na ktorú ste klikli,
        na našej internetovej lokalite (<a href=""><?= $domenaNazov ?></a>) nie je <span class="text-nowrap">(alebo už nie je)</span> k dispozícii.
    </h4>
</div>




