<div class="info-okno-rolovanie">
    <div class="container container-fluid">
        <h1 class="display-3"><?= $clanok['titulok'] ?></h1>
        <div class="lead font-weight-bolder"><?= $_clanok['obsah'] ?></div>
        <div class="text-center mt-5">
            <a href="cookies/uloz/<?= $nazov ?>?presmeruj=<?= $presmeruj ?>" class="btn btn-lg btn-dark">Rozumiem</a>
        </div>
    </div>
</div>
