<ul class="nav align-items-end flex-nowrap mt-1">
    <li class="nav-item  ">
        <a class="nav-link bg-danger odkaz p-1 m-1 d-flex align-items-end" id="avatar" href="administracia/osobne-udaje">
            <img src="obrazky/uzivatel/ikona.png" title=Účet alt="foto">
            <span class="font-italic align-bottom text-warning mr-2"><?= $_meno ?></span>
        </a>
    </li>
    <li class="nav-item">
        <small><a class="nav-link odkaz" href="prihlasit/odhlasit?presmeruj=<?= $presmeruj ?>">Odhlásiť</a></small>
    </li>
</ul>