<h4>Zabudnuté heslo na <a href="https://<?= $domena ?>"><?= $domenaNazov ?></a></h4>
<div class="centruj">
    <h6>Dobrý deň, na našej stránke <a href="https://<?= $domena ?>"><?= $domenaNazov ?></a> ste požiadali o generovanie nového hesla.</h6>
    <p>Nové prihlasovacie heslo pre Váš učet je:</p>
    <table>
        <tr>
            <th>Prihlasovací E-mail:</th>
            <td><?= $email ?></td>
        </tr>
        <tr>
            <th>Nové heslo:</th>
            <td><?= $heslo ?></td>
        </tr>
    </table>
    <br>
    <p>Heslo si možte zmeniť po prihlaseni na <a href="https://<?= $domena ?>/">tejto adrese</a></p>

</div>