<?php use App\RezervaciaModul\Model\PermanentkaTypManazer;
use App\RezervaciaModul\Model\PermanentkaManazer;
use App\RezervaciaModul\Model\RezervaciaManazer;
use App\AdministraciaModul\Uzivatel\Model\OsobaDetailManazer;
use App\AdministraciaModul\Uzivatel\Model\TrenerManazer;?>

<div class="d-flex justify-content-center">
    <form method="post" id="<?= $_formular['formularId'] ?>" class="form-inline my-1 justify-content-md-start justify-content-center" onchange="klikniSubmit()">
        <?= $_formular['csrf'] ?>
        <div>
            <?= $_formular['rezervacia_vyber'] ?>
        </div>
        <div >
            <?= $_formular['zobrazit'] ?>
        </div>
    </form>
    <script src="js/klikniSubmit.js"></script>
</div>

<div class="d-flex justify-content-center">
    <table class="w-auto table table-hover table-sm table-bordered table-striped table-dark table-responsive-md">
        <thead class="bg-danger">
        <tr>
            <th class="text-center">P.č</th>
            <?= $vyber === 'dnes' || $vyber === 'zajtra'  ? '' : '<th>Dátum</th>' ?>
            <th>Meno Priezvisko</th>
            <th>Príchod</th>
            <th>Odchod</th>
            <th>Permanentka</th>
            <th>Dátum vytvorenia</th>
            <th class="text-center">Edit.</th>
        </tr>
        </thead>
        <tbody>

        <?php $dnes = new DateTime(); $poradie = 1; ?>
        <?php foreach ($rezervacie as $rezervaciaId => $rezervacia) : ?>

            <?php $buducnost = (new DateTime($rezervacia[RezervaciaManazer::DATUM] . ' ' . $rezervacia[RezervaciaManazer::CAS_OD])) >= $dnes ; //pitam sa či je to skupinový trening ?>

            <tr class="<?= $buducnost ?  isset($rezervacia['klient']) ? 'font-weight-bold' : 'text-warning' : 'text-secondary' ?>" <?= isset($rezervacia['klient']) ? 'style="color:' . $rezervacia['trener'][TrenerManazer::FARBA] . '"' : '' ?>>
                <td class="text-center text-white"><?= $poradie ?>.</td>

                <?= $vyber === 'dnes' || $vyber === 'zajtra'  ? '' :
                    '<td>' . FormatPomocne::peknyDatum($rezervacia[RezervaciaManazer::DATUM]) . ' 
                            <small class="small">
                                ('. FormatPomocne::denSlovensky($rezervacia[RezervaciaManazer::DATUM]) . ')
                            </small>
                        </td>' ?>
                <td>
                    <a href="administracia/osobne-udaje/<?= $rezervacia['rezervacia_uzivatel_id']?>">

                        <?= isset($rezervacia['klient']) ? $rezervacia['trener'][TrenerManazer::PREZIVKA] :
                            $rezervacia['rezervacia_meno'] . ' ' . $rezervacia['rezervacia_priezvisko'] ?>
                    </a>
                </td>

                <td class="text-center"><?= $rezervacia[RezervaciaManazer::CAS_OD] ?></td>
                <td class="text-center"><?= $rezervacia[RezervaciaManazer::CAS_DO] ?></td>

                <td>
                    <span class="font-weight-normal btn-block btn-sm text-center <?= $rezervacia['permanentka']['nazov'] === 'Neaktívna' ? ' btn-secondary' : ' btn-success' ?>"><?= $rezervacia['permanentka']['nazov'] ?></span>
                </td>

                <td>
                    <?= FormatPomocne::formatujDatumCasNaTvar($rezervacia[RezervaciaManazer::DATUM_VYTVORENIA], 'j.n.Y / G:i:s') ?>
                </td>

                <td class="text-center">
                    <?=
                        DialogPomocne::zostavDialogOdstranenia($rezervaciaId, 'rezervacia/zrus-rezervaciu/' . $rezervaciaId . '?presmeruj=administracia/sprava-uzivatelov/rezervacie/' . $vyber, 'Skutočne si prajete odstrániť rezerváciu?');
                    ?>
                </td>
                <?php $poradie++ ?>
            </tr>
            <?php if (isset($rezervacia['klient'])): ?>
                <tr <?= $buducnost ? 'style="color:' . $rezervacia['trener'][TrenerManazer::FARBA] . '"' : 'class="text-secondary"' ?>>
                    <td colspan="1"></td>
                    <td colspan="<?= $vyber === 'vsetky' ? '7' : '6' ?>" class="small">
                        <i class="fa fa-arrow-up"></i>
                    <?php foreach ($rezervacia['klient'] as $klient) : ?>
                            <a href="administracia/osobne-udaje/<?= $klient['klient_uzivatel_id']?>">

                                <?= $klient['klient_meno'] . ' ' . $klient['klient_priezvisko'] ?>
                            </a>
                        <i class="fa fa-arrow-up"></i>
                    <?php endforeach; ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
