<?php use App\ClanokModul\Model\ClanokManazer;
      use App\ClanokModul\Model\ClanokTypManazer; ?>
<?= $menu->vypisPohlad() ?>


<div class="d-flex justify-content-center">
    <form method="post" id="<?= $_formular['formularId'] ?>" class="form-inline my-1 justify-content-md-start justify-content-center" onchange="klikniSubmit()">
        <?= $_formular['csrf'] ?>
        <div>
            <?= $_formular[ClanokTypManazer::URL] ?>
        </div>
        <div >
            <?= $_formular['zobrazit'] ?>
        </div>
    </form>
    <script src="js/klikniSubmit.js"></script>
</div>


<div class="d-flex justify-content-center">
    <table class="table table-sm table-bordered table-striped w-auto table-dark">
        <tr class="text-center">
            <th>P.č.</th>
            <th>Typ článku</th>
            <th>Titulok</th>
            <th>Verejný</th>
            <th>Edit.</th>
        </tr>
        <?php $poradie = 1; ?>
        <?php foreach ($clanky as $clanok) : ?>
            <tr class="">
                <td class="text-center">
                    <strong><?= $poradie++ ?>.</strong>
                </td>
                <td class="text-center">
                    <strong><?= $clanok[ClanokTypManazer::NAZOV] ?></strong>
                </td>

                <td class="">
                    <strong><a href="<?= $clanok['typ_url'] ?>/<?= $clanok[ClanokManazer::URL] ?>"><?= $clanok[ClanokManazer::TITULOK] ?></a></strong>
                    <small>(<?= FormatPomocne::skrat($clanok[ClanokManazer::POPISOK],35) ?>)</small>
                </td>

                <td class="text-center text-white <?= $clanok[ClanokManazer::VEREJNY] ? 'bg-success' : 'bg-dark'?>">
                    <?= $clanok['verejny_nazov'] ?>
                </td>

                <td class="align-middle text-center text-nowrap">
                    <a href="administracia/editor/clanok/<?= $clanok[ClanokManazer::URL] ?>?presmeruj=<?= $presmeruj ?>" class="btn btn-light btn-sm border-dark kontrolka"><i title="Editovať" class="fa fa-pencil-alt"></i></a>
                    <?= DialogPomocne::zostavDialogOdstranenia($clanok[ClanokManazer::CLANOK_ID], 'administracia/odstran/clanok/' . $clanok[ClanokManazer::URL], 'Skutočne si prajete odstrániť vybraný Článok?') ?>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
</div>