<div class="row mx-1 text-white no-gutters py-2">
    <div class="offset-0 col-9 col-md-10 offset-xl-1 col-xl-10 px-2 text-center d-flex align-items-center justify-content-center">
        <h6><?= $_popisok ?><a href="clanok/cookies"> Viac informácií</a></h6>
    </div>
    <div class="col-3 col-md-2  col-xl-1 d-flex align-items-center justify-content-center">
        <a href="cookies/uloz/<?= $nazov ?>?presmeruj=<?= $presmeruj ?>" class="btn btn-outline-primary text-white">Súhlasím</a>
    </div>
</div>

